### ISSUE TITLE
Book Pg-7: paket.dependencies instructions

### ISSUE THREAD

**Issue by keithn** [demystifyfp/FsTweet#2]
implies you can echo to the file.  Not sure that works as the author expects in powershell.   

you end up with something like :-

source https://www.nuget.org/api/v2
f r a m e w o r k :   n e t 4 6 1

**Comment by demystifyfp** [comment]
Hi @keithn,

The command "echo" is not supported in Powershell. You need to use either "ubuntu bash" or "Cygwin".

Sorry, for mentioning it as just "command line interface" in the book. Will fix this in the next update.

As mentioned in the book, it is just a preference. You can open the file and manually enter it.

**Comment by demystifyfp** [comment]
Hi @keithn,

Thank you for reporting it. It has been addressed in the recent update of the book.
